language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- export BUILD_LIFE=${TRAVIS_COMMIT:0:7}
- ant run-tests
script:
- ant -DbuildLife=${BUILD_LIFE}
jdk:
- oraclejdk8
- openjdk7
notifications:
  slack:
    secure: rDlBNXG1nxlD06IKNNLJ3XTh65OPArhTGWNK3oRI5b893I2Lybab135bhBCG7SXgbUuoMuOsJOfxFAgOqt50l1fqabCFr79CowigVUhCBQLjln50fhiwcDKw2Ob6S8I0ctL1JbJd0VDtXDXjfzEW9VmqYDIZn4JTs0sJZ/VJIVBr5VaUWnttvhKASFXznffnLijVjCJw4ih/uVSJOCLsQDKcVURrmb992eWVbZXSFyDkI1CHWFD0jCqLlx2OL7gkHtXBR9V6u3YM+BNpJ1jsWlrSjPDzkC03naF1Uq+0vgYzXsV5dM5oR1oH/8xA+WJUt7ILH5dvGqYkAJwaSpqzPYVhX4BN2GO+F3qvxnxBssTu/hAnwzej5A/CoqgcWo4BtVhSm6Yi5chpZWUjkoI+e3JaTYnkdhfINuWnHtTkqK6HLT2KWQ7o5VUooWYwYXoDQ6bOM0aTbUgmMiXHjG6GFRkjxDDCGpwznOBWRmJe1e0Wfh2GIw6woBLBgIw+rRHhnJsIsjpus2G/KD6T9rImkWS1vfgVRULLnDIwVFg40MHOESh4YnxFOhL18Iy/R73lupSfH5sQQNHUGRhrsBwF0Xm9wcL/S9q+otP9yYzrexGp5gVebic1feOJgUgT/pmYGeLGH5D+fRfVg2aGavBamyv0/DznOO8kBmn1IgFMgCA=
    on_success: change
    on_failure: change
  email: false
deploy:
  provider: releases
  api_key:
    secure: E89jwk4S/HOJBdXXRjbTLhal5yopKeBLlRcJZ3ZmMSIBxLxBzXU2eUE+2PsXnEHApRHiDO/Sv12UD7cIi+7wDwvaxn8TWOW4sN/1wRfpDOhbu7GUNsIC17kaW34vR0lfsdB47r8X0edFcoO+lM4ukPSGhBIBnWu6vwtpSoENKfwUWHEfs5rxsa5JaxdQSr6WfQVS/TqquxjYOSuQRTzoVTPATdZ9n9/hr9Tz6Zrbh9EIEMkNsbPYggr/Z5T806qqnRC/cHILZVdA4leMk0azhC3sebPHnmwjxClewrVeW9aGxd8eTftak2LjUGIXJbAKSMLxTB+6wdCjrot6Rw08VCceEK3d5TRQF+1lbOjl5ASXuACiY72JlfbKEMx54qi/P2SEfhLD6m+LUk4I849YgM2vskUoxYIGAbL8Bt0gTfczpGTDaK8xWRJfYkuyXQih1VfNnts74yE3Xhsg736NczZdHAP86DN9jRnxX8/wlZcKQUW/UJFQV6pJKoo9xwXfPNpgcEV63hJi8a04yaYCkiK9daIJFiMYQj88P5Xp4akY3NIGFxOOQuCwxJPOHBSHHpl6gWUgWW37jy5dJ8c+Cvyu2Tw18JYV7lZcZ+PmmHNIZanKGAJc9NEAyZBw8xqspqpWwrJEw4pAaRDx9mixD3UPMJ4/T7lu+wUXBmRaoio=
  file_glob: true
  file: releases/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: IBM-UrbanCode/Informatica-UCD
